services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: to-do-list
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/BaseCrud?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
